### 모든 식당 메뉴 조회
GET http://localhost/menu

### 한 식당 메뉴 전체 조회
GET http://localhost/menu?restSeq=2

### 메뉴 추가
POST http://localhost/menu
Content-Type: application/json

{
  "name": "순두부찌개",
  "price": 8900,
  "imgLink": "https://images.yogiyo.co.kr/image/yogiyo/REST_OWNER_IMG/OWNERS/566021/20210621_143630_blob?width=384&height=273&quality=100",
  "restaurant": {
    "seq": 2
  }
}

### 메뉴 상세 조회
GET http://localhost/menu/1

### 메뉴 삭제
DELETE http://localhost/menu/4
