### 모든 식당 메뉴 조회
GET http://localhost/menu

### 한 식당 메뉴 전체 조회
GET http://localhost/menu?restSeq=2

### 메뉴 추가
POST http://localhost/menu
Content-Type: application/json

{
  "name": "김치찌개",
  "price": 9500,
  "imgLink": "kimchi_temp",
  "restaurant": {
    "seq": 1
  }
}

### 메뉴 상세 조회
GET http://localhost/menu/1

### 메뉴 삭제
DELETE http://localhost/menu/4
