### 주문 생성
POST http://localhost/orders
Content-Type: application/json

{
  "restaurant": {
    "seq": 2
  },
  "user": {
    "seq": 1
  }
}

### 주문 조회
GET http://localhost/orders/9

### 주문 삭제
DELETE http://localhost/orders/9
Content-Type: application/json

{
  "user": {
    "seq": 1
  }
}

### 주문 수정
PATCH http://localhost/orders/8
Content-Type: application/json

{
  "seq": 8,
  "status": "ORDER",
  "restaurant": {
    "seq": 2
  },
  "user": {
    "seq": 2
  }
}

### 주문에 참여 생성
POST http://localhost/orders/9
Content-Type: application/json

{
  "user": {
    "seq": 2
  },
  "menu": {
    "seq": 1,
    "name": "아메리카노",
    "price": 3500,
    "imgLink": "americano_temp"
  },
  "order": {
    "user": {
      "seq": 1
    }
  }
}